export const FOVOURITE_REQUEST_ACTIONS = 'FOVOURITE_REQUEST_ACTIONS';
export const ADD_ITEM = 'ADD_ITEM';
export const FOVOURITE_REQUEST_FAILURE = 'FOVOURITE_REQUEST_FAILURE';
export const ADD_DATA = 'ADD_DATA';
